/**
 * @packageDocumentation
 * @module api.functional.sign_out
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";

/**
 * @controller AccountController.signOut()
 * @path GET /sign-out
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function signOut
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        signOut.ENCRYPTED,
        signOut.METHOD,
        signOut.path()
    );
}
export namespace signOut
{

    export const METHOD = "GET" as const;
    export const PATH: string = "/sign-out";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-out`;
    }
}