/**
 * @packageDocumentation
 * @module api.functional.sign_in
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";

/**
 * @controller AccountController.signIn()
 * @path GET /sign-in
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function signIn
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        signIn.ENCRYPTED,
        signIn.METHOD,
        signIn.path()
    );
}
export namespace signIn
{

    export const METHOD = "GET" as const;
    export const PATH: string = "/sign-in";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-in`;
    }
}