/**
 * @packageDocumentation
 * @module api.functional.oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";

import type { __type } from "./../../../../src/api/account/presentation/account.controller";

/**
 * 로그인 인증 성공시 redirect되는 경로. 인증 성공시 세션을 생성하고 access token과 함께 쿠키에 추가됩니다.
 * 
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param profile 구글 인증을 통해 얻은 프로필 데이터입니다.
 * @returns 로그인 API 요청시 생성된 토큰 정보를 포함합니다.
 * 
 * @controller AccountController.callback()
 * @path GET /oauth/callback
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function callback
    (
        connection: IConnection
    ): Promise<callback.Output>
{
    return Fetcher.fetch
    (
        connection,
        callback.ENCRYPTED,
        callback.METHOD,
        callback.path()
    );
}
export namespace callback
{
    export type Output = __type;

    export const METHOD = "GET" as const;
    export const PATH: string = "/oauth/callback";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/oauth/callback`;
    }
}